### ISSUE TITLE
Cannot connect to MySQL database without sqlbag trying to load postgres drivers.

### ISSUE THREAD

**Issue by neonstreams** [djrobstep/sqlbag#1]
Upon trying to perform a simple MySQL db connection, there were a number of errors as sqlbag tries to load the postgres drivers also. Will add a stacktrace soon.

**Comment by djrobstep** [comment]
Thanks for reporting this, MySQL support has been a lower priority than postgres, as you've discovered.

Two ways to fix this.. catch and ignore the import error, or not import any postgres stuff at top level. First way is probably easier and changes the api less.

**Comment by djrobstep** [comment]
Fixed now
