### ISSUE TITLE
BUG: Mutates dictionary while iterating over it

### ISSUE THREAD

**Issue by bianca-actu** [djrobstep/sqlbag#4]
`parse_interval_values` in `sqlbag/pg/datetimes.py` mutates the dictionary while iterating over it when the key doesn't end in 's', which throws a "RuntimeError: dictionary keys changed during iteration".
For example, calling it with `parse_interval_values('1 day')` throws the error.

**Comment by bianca-actu** [comment]
The error is only raised in python 3.8, but adding new keys to a dict while iterating over it isn't a great idea in any case.

**Comment by djrobstep** [comment]
Good catch. Just did a new release fixing this: https://pypi.org/project/sqlbag/0.1.1579049654/

**Comment by bianca-actu** [comment]
Thanks, that was quick!
